import { Expense } from "./interfaces";

export const expensesList: Expense[] = [
  {
    id: 1,
    type: "expense",
    categoryId: 7,
    amount: 282,
    date: "Sun Dec 22 2024",
    user: "admin",
  },
  {
    id: 2,
    type: "income",
    categoryId: 2,
    amount: 50,
    date: "Sun Dec 22 2024",
    user: "jsantos",
  },
  {
    id: 3,
    type: "expense",
    categoryId: 4,
    amount: 130,
    date: "Sun Dec 22 2024",
    user: "admin",
  },
  {
    id: 4,
    type: "expense",
    categoryId: 3,
    amount: 95,
    date: "Sun Dec 22 2024",
    user: "jsantos",
  },
  {
    id: 5,
    type: "income",
    categoryId: 9,
    amount: 200,
    date: "Sun Dec 22 2024",
    user: "admin",
  },
  {
    id: 6,
    type: "expense",
    categoryId: 2,
    amount: 225,
    date: "Sun Dec 22 2024",
    user: "jsantos",
  },
  {
    id: 7,
    type: "expense",
    categoryId: 1,
    amount: 400,
    date: "Sun Dec 22 2024",
    user: "admin",
  },
  {
    id: 8,
    type: "income",
    categoryId: 7,
    amount: 50,
    date: "Sun Dec 22 2024",
    user: "jsantos",
  },
  {
    id: 9,
    type: "expense",
    categoryId: 4,
    amount: 350,
    date: "Sun Dec 22 2024",
    user: "admin",
  },
  {
    id: 10,
    type: "income",
    categoryId: 6,
    amount: 60,
    date: "Sun Dec 22 2024",
    user: "jsantos",
  },
];
